doctrine:
    dbal:
        # Configuration for databases server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

       #with symfony 3.3, remove the 'resolve': prefix
        url: '%env(resolve:DATABASE_URL)%'
       #Avoid migration command to find session or user_micro_post table in database
        schema_filter: ~^(?!sessions|user_micro_post)~


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        #Rules for generating  table names, field names by default it's the_table_name
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        #Automatically look for mapping configuration
        auto_mapping: true
        mappings:
            #Entity mapping for App namespace
            App:
                is_bundle: false
                #Is of type annotation (could also be XML, YAML)
                type: annotation
                #Entities could be found in directory
                dir: '%kernel.project_dir%/src/Entity'
                #Entiy namespace prefix is
                prefix: 'App\Entity'
                #Shorthand alias is App, eg. App:Post, App:User
                alias: App
