version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browsers-legacy
        environment:
          APP_ENV: test
          DATABASE_URL: mysql://admin:admin@127.0.0.1:3306/micro-post
          MAILER_FROM: micro@micro.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:5.2
        environment:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: micro-post
    steps:
      - checkout
      - run:
          name: Install PHP MYSQL
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test -n

