# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    hello_m : "Hello from service -> "

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public : false # This allow to fetch service directly from the container via $container->get('aliasId')

        bind:                    #Automatically define default argument
            $message: '%hello_m%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    #Recuperer les variables globales dans l'extension créée à la main
    App\Twig\AppExtension:
        arguments:
            $locale: '%locale%'

    #    App\Service\Greeting:
    #        arguments:
    #            $message: '%hello_m%'

    app.greeting:
        public:  true
        alias: App\Service\Greeting

    # App\Controller\BlogController: ['@App\Service\Greeting']

    # App\Service\Greeting: ['@monolog.logger']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
